- name: users | marci | remove preinstalled clutter from home directory
  file:
    path: /home/marci/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: users | marci | create personal config directories
  tags: dotfiles,dotfiles-marci
  file:
    path: /home/marci/{{ item.dir }}
    state: directory
    owner: marci
    group: marci
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: projects }
    - { dir: templates }

- name: users | marci | copy user-dirs.dirs
  tags: dotfiles,dotfiles-marci
  copy:
    src: users/marci/user-dirs.dirs
    dest: /home/marci/.config/user-dirs.dirs
    owner: marci
    group: marci
    mode: 0600
  notify: update_xdg

- name: users | marci | copy personal config files
  tags: dotfiles,dotfiles-marci
  copy:
    src: users/marci/{{ item.src }}
    dest: /home/marci/{{ item.dest }}
    owner: marci
    group: marci
    mode: 0600
  with_items:
    - { src: 'asunder', dest: '.asunder' }
    - { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
    - { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }  
    - { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
    - { src: 'terminator_config', dest: '.config/terminator/config' }

