# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/marci.yml

#
  ## system setup
  - import_tasks: system_setup/autofs.yml
  - import_tasks: system_setup/scripts.yml
  - import_tasks: system_setup/tweaks.yml

  ## install software
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/darktable.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/packer.yml
  - import_tasks: software/signal.yml
  - import_tasks: software/terraform.yml
  - import_tasks: software/thunderbird.yml
  - import_tasks: software/todoist.yml
  - import_tasks: software/vagrant.yml

  rescue:
    - set_fact: task_failed=true