- name: software | signal | install package
  tags: packages,flatpak,signal,workstation-packages
  become_user: marci
  flatpak:
    name: org.signal.Signal
    method: user
    state: present
  when: signal is defined and signal == true

- name: software | signal | enable autostart
  tags: packages,flatpak,signal,workstation-packages
  file:
    src: /home/marci/.local/share/flatpak/exports/share/applications/org.signal.Signal.desktop
    dest: /home/marci/.config/autostart/org.signal.Signal.desktop
    owner: marci
    group: marci
    state: link
  when: signal is defined and signal == true