# note: snap packages not automated in arch yet, snapd is not available in repo
- name: software | todoist | install package
  tags: packages,snap,todoist,workstation-packages
  snap:
    name:  todoist
    state: present
 

- name: software | todoist | enable autostart
  tags: packages,todoist,snap,workstation-packages
  file:
    src: /var/lib/snapd/desktop/applications/todoist_todoist.desktop
    dest: /home/marci/.config/autostart/todoist_todoist.desktop
    owner: marci
    group: marci
    state: link
 